from __future__ import annotations

import argparse
import json
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import psycopg
from psycopg import Connection
from psycopg.types.json import Jsonb

from .profiles import PROFILE_COLUMNS, PROFILE_OWNER_COLUMN
from .session_archive import ARCHIVE_COLUMNS, ARCHIVE_OWNER_COLUMN
from .settings import get_settings


@dataclass(frozen=True)
class MigrationSnapshot:
    profiles: list[dict[str, Any]]
    session_archives: list[dict[str, Any]]

    @property
    def total_rows(self) -> int:
        return len(self.profiles) + len(self.session_archives)


PROFILE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS equipment_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INTEGER,
    name TEXT NOT NULL,
    site_name TEXT NOT NULL,
    latitude_deg DOUBLE PRECISION NOT NULL,
    longitude_deg DOUBLE PRECISION NOT NULL,
    timezone TEXT NOT NULL,
    bortle INTEGER NOT NULL,
    telescope_name TEXT NOT NULL,
    telescope_type TEXT NOT NULL,
    aperture_mm DOUBLE PRECISION NOT NULL,
    focal_length_mm DOUBLE PRECISION NOT NULL,
    reducer_name TEXT NOT NULL,
    reducer DOUBLE PRECISION NOT NULL,
    camera_name TEXT NOT NULL,
    sensor_id TEXT NOT NULL,
    sensor_name TEXT NOT NULL,
    sensor_width_mm DOUBLE PRECISION NOT NULL,
    sensor_height_mm DOUBLE PRECISION NOT NULL,
    pixel_size_um DOUBLE PRECISION NOT NULL,
    filter_set TEXT NOT NULL,
    filter_wheel TEXT NOT NULL,
    guiding_setup TEXT NOT NULL,
    guide_camera_name TEXT NOT NULL,
    focuser_name TEXT NOT NULL,
    mount_name TEXT NOT NULL,
    updated_at TEXT NOT NULL
)
"""

ARCHIVE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS session_archives (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INTEGER,
    target_id TEXT NOT NULL,
    target_name TEXT NOT NULL,
    session_date DATE NOT NULL,
    status TEXT NOT NULL,
    profile_id INTEGER,
    profile_name TEXT,
    site_name TEXT NOT NULL,
    bortle INTEGER NOT NULL,
    fov_horizontal_deg DOUBLE PRECISION NOT NULL,
    fov_vertical_deg DOUBLE PRECISION NOT NULL,
    pixel_scale_arcsec DOUBLE PRECISION NOT NULL,
    imaging_mode TEXT NOT NULL,
    filter_names JSONB NOT NULL,
    total_integration_minutes INTEGER NOT NULL,
    planned_frames INTEGER NOT NULL,
    captured_frames INTEGER NOT NULL,
    window_start TEXT NOT NULL,
    window_end TEXT NOT NULL,
    weather_status TEXT NOT NULL,
    weather_score INTEGER NOT NULL,
    moon_illumination_percent INTEGER NOT NULL,
    white_night BOOLEAN NOT NULL,
    notes TEXT NOT NULL,
    capture_markdown TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
)
"""


def sqlite_path_from_url(sqlite_url: str) -> str:
    if sqlite_url == "sqlite:///:memory:":
        return ":memory:"
    if sqlite_url.startswith("sqlite:///"):
        return sqlite_url.removeprefix("sqlite:///")
    if sqlite_url.startswith("sqlite://"):
        return sqlite_url.removeprefix("sqlite://")
    raise ValueError("Only sqlite:// URLs are supported as migration source")


def read_sqlite_snapshot(sqlite_url: str) -> MigrationSnapshot:
    path = sqlite_path_from_url(sqlite_url)
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    try:
        profile_rows = read_table_rows(
            connection, "equipment_profiles", [PROFILE_OWNER_COLUMN, *PROFILE_COLUMNS]
        )
        archive_rows = read_table_rows(
            connection, "session_archives", [ARCHIVE_OWNER_COLUMN, *ARCHIVE_COLUMNS]
        )
    finally:
        connection.close()

    return MigrationSnapshot(
        profiles=[dict(row) for row in profile_rows],
        session_archives=[normalize_archive_row(dict(row)) for row in archive_rows],
    )


def read_table_rows(
    connection: sqlite3.Connection, table_name: str, columns: list[str]
) -> list[sqlite3.Row]:
    if not sqlite_table_exists(connection, table_name):
        return []
    existing_columns = {
        row["name"] for row in connection.execute(f"PRAGMA table_info({table_name})")
    }
    select_expressions = [
        column if column in existing_columns else f"NULL AS {column}" for column in columns
    ]
    return connection.execute(
        f"SELECT {', '.join(select_expressions)} FROM {table_name} ORDER BY id"
    ).fetchall()


def sqlite_table_exists(connection: sqlite3.Connection, table_name: str) -> bool:
    row = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table_name,),
    ).fetchone()
    return row is not None


def normalize_archive_row(row: dict[str, Any]) -> dict[str, Any]:
    row["filter_names"] = json.loads(row["filter_names"])
    row["white_night"] = sqlite_bool(row["white_night"])
    return row


def sqlite_bool(value: Any) -> bool:
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y"}
    return bool(value)


def migrate_sqlite_to_postgres(
    sqlite_url: str,
    postgres_url: str,
    *,
    dry_run: bool = False,
) -> MigrationSnapshot:
    snapshot = read_sqlite_snapshot(sqlite_url)
    if dry_run:
        return snapshot

    with psycopg.connect(psycopg_connection_url(postgres_url)) as connection:
        create_postgres_schema(connection)
        upsert_rows(connection, "equipment_profiles", PROFILE_COLUMNS, snapshot.profiles)
        upsert_rows(
            connection,
            "session_archives",
            ARCHIVE_COLUMNS,
            [prepare_archive_for_postgres(row) for row in snapshot.session_archives],
        )
        reset_identity_sequence(connection, "equipment_profiles")
        reset_identity_sequence(connection, "session_archives")
        connection.commit()

    return snapshot


def create_postgres_schema(connection: Connection[Any]) -> None:
    with connection.cursor() as cursor:
        cursor.execute(PROFILE_TABLE_SQL)
        cursor.execute(ARCHIVE_TABLE_SQL)
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_session_archives_session_date
            ON session_archives (session_date DESC, id DESC)
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_session_archives_target
            ON session_archives (target_id)
            """
        )


def psycopg_connection_url(postgres_url: str) -> str:
    return postgres_url.replace("postgresql+psycopg://", "postgresql://", 1)


def upsert_rows(
    connection: Connection[Any],
    table_name: str,
    columns: list[str],
    rows: list[dict[str, Any]],
) -> None:
    if not rows:
        return

    placeholders = ", ".join(["%s"] * len(columns))
    assignments = ", ".join(f"{column} = EXCLUDED.{column}" for column in columns if column != "id")
    sql = f"""
        INSERT INTO {table_name} ({", ".join(columns)})
        VALUES ({placeholders})
        ON CONFLICT (id) DO UPDATE SET {assignments}
    """
    values = [[row[column] for column in columns] for row in rows]

    with connection.cursor() as cursor:
        cursor.executemany(sql, values)


def prepare_archive_for_postgres(row: dict[str, Any]) -> dict[str, Any]:
    return {
        **row,
        "filter_names": Jsonb(row["filter_names"]),
    }


def reset_identity_sequence(connection: Connection[Any], table_name: str) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT pg_get_serial_sequence(%s, 'id')
            """,
            (table_name,),
        )
        sequence_name = cursor.fetchone()[0]
        if sequence_name is None:
            return
        cursor.execute(f"SELECT COALESCE(MAX(id), 0) FROM {table_name}")
        max_id = cursor.fetchone()[0]
        if max_id:
            cursor.execute("SELECT setval(%s, %s, true)", (sequence_name, max_id))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prototype migration from Astrofoto SQLite storage to PostgreSQL."
    )
    parser.add_argument(
        "--sqlite-url",
        default=get_settings().profile_database_url,
        help="SQLite source URL, for example sqlite:////data/astrofoto.sqlite3.",
    )
    parser.add_argument(
        "--postgres-url",
        default=get_settings().database_url,
        help="PostgreSQL target URL, for example postgresql+psycopg://user:pass@postgres:5432/db.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Read SQLite and print counts without writing to PostgreSQL.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    sqlite_path = sqlite_path_from_url(args.sqlite_url)
    if sqlite_path != ":memory:" and not Path(sqlite_path).exists():
        raise SystemExit(f"SQLite source does not exist: {sqlite_path}")

    snapshot = migrate_sqlite_to_postgres(
        sqlite_url=args.sqlite_url,
        postgres_url=args.postgres_url,
        dry_run=args.dry_run,
    )
    mode = "Dry run" if args.dry_run else "Migrated"
    print(
        f"{mode}: {len(snapshot.profiles)} profiles, "
        f"{len(snapshot.session_archives)} session archives, {snapshot.total_rows} rows total."
    )


if __name__ == "__main__":
    main()
